#### Load packages ####
library(here)
library(XML)
library(reader)
library(fs)
library(feather)
library(tidyverse)
library(peekds) 
library(osfr)

# load 
source(here("data/reflook_v1/import_scripts/import_helpers.R"))

#### general parameters ####
dataset_name <- "reflook_v1"
dataset_id <- 0
max_lines_search <- 40 #maybe change this value?
subid_name <- "Subject"
monitor_size <- "Calibration Area"
sample_rate <- "Sample Rate"
possible_delims <- c("\t",",")
left_x_col_name <-  "L POR X [px]"
right_x_col_name <-  "R POR X [px]"
left_y_col_name <-  "L POR Y [px]"
right_y_col_name <-  "R POR Y [px]"
stims_to_remove_chars <- c(".avi")
stims_to_keep_chars <- c("_")
trial_file_name <- "reflook_tests.csv"
participant_file_name <- "reflook_v1_demographics.csv"

#### Pull in data from OSF ####
dir_path <- fs::path(here::here("data", dataset_name, "raw_data"))

##only download if it's not on your machine
if(length(list.files(paste0(dir_path, "/full_dataset"))) == 0 && length(list.files(paste0(dir_path, "/experiment_info"))) == 0) {
  get_raw_data(lab_dataset_id = "reflook_v1", path = dir_path, osf_address = "pr6wu")
}

#Specify file 
# file_name <- "Reflook4_2 (3)_080212_02_1825 Samples.txt"

#### define directory ####
# Define root path
project_root <- here::here()

# build directory path
dir_path <- fs::path(project_root, "data", dataset_name, "raw_data", "full_dataset")
exp_info_path <- fs::path(project_root, "data", dataset_name, "raw_data", "experiment_info")
aoi_path <- fs::path(project_root, "data", dataset_name, "raw_data", "test_aois")

#output path
output_path <- fs::path(project_root, "data", dataset_name,"processed_data")

#### Run SMI import cycle ####
process_smi(dir = dir_path, exp_info_dir = exp_info_path)

#### Generate AOIS ####
aoi_timepoints <- peekds::generate_aoi(dir = output_path) %>%
  mutate(aoi = ifelse(is.na(aoi), "missing", as.character(aoi))) #NAs generated by generate_aois, change to missing

# write to file
write_csv(aoi_timepoints, file = paste0(output_path, "/", "aoi_timepoints.csv"))

# run validator
peekds::validate_for_db_import(dir_csv=output_path)


